name: snakemake

channels:
  - nodefaults       # explicitly list all channels here
  - conda-forge
  - bioconda

dependencies:        # if a version isn't specified, the latest compatible stable version is used
  - python=3.9.*
  - poetry=1.*
  - snakemake=7.9.0
  - mamba
  - pip
  - conda-lock
  # list add any additional dependencies to be installed by conda rather than poetry


platforms: # Non-standard section listing target platforms for conda-lock:
  - linux-64
